[package]
name = "kn-core"
version = "0.1.0"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"

[dependencies]
kanji = { version = "2.0", features = ["serde"] }
itertools = "0.10"
petgraph = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

