[package]
name = "kin"
version = "0.1.0"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"

[dependencies]
gumdrop = "0.8"
kn-core = { path = "../kn-core" }

[profile.release]
lto = true
