[package]
name = "kin"
version = "0.1.0"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"

[dependencies]
kn-core = { path = "../kn-core" }
rusqlite = "0.24"

[profile.release]
lto = true
